version: '3'

volumes:
  pg_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /staticfiles/
    volumes:
    - static:/staticfiles
  gateway:
    build: ./nginx/
    ports:
      - '8080:80'
    volumes:
      - static:/static
      - media:/media