version: '3'

volumes:
  pg_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: pavlovdabjj/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
      - media_volume:/media
  frontend:
    image: pavlovdabjj/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /staticfiles/
    volumes:
      - static_volume:/staticfiles
  gateway:
    image: pavlovdabjj/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/static/
      - media_volume:/media/
    ports:
      - '9000:80'
